# Site settings
title: Li Qinqi
url: "http://liqinqi.com"

# Build settings
markdown: kramdown
include: [".htaccess"]
permalink: /:year/:title.html
highlighter: pygments
paginate: 10

# Disqus
disqus: liqinqi

# Lychee settings
lychee:
  url: http://gallery.liqinqi.com/
  album_title_tag: h1
