# Site settings
title: Family Blog
years: 2012-2014

# Build settings
markdown: kramdown
include: [".htaccess"]
permalink: /:year/:title.html
paginate: 10

# Disqus
disqus: liqinqi

# Gallery
gallery:
    url: http://gallery.limaoxu.com
    path: /gallery/
    title_tag: h1
    link_to: gallery
    cache_folder: _gallery_cache
    
